Basic header structure #3
front-end-by-rimantas/16-grupe-portfolio-leverage pull request #38
Opened 2020-08-16 10:18 UTC by IngriJ

* Basic header structure (placeholders)

// Strigau ir nesutvarkau nušokusio taško po Leverage. Gal turit minčių? inlineblock neveikia..

2020-08-16 10:57 UTC, wycka0214 commented
![header](https://user-images.githubusercontent.com/66961507/90332726-af3d5000-dfbf-11ea-9eb7-1b2b9cbd70ea.png)

man tai rodo taip basic, bet speju del to kad pradeta buvo daryti kol nebuvo btn nei fontawesome iconu 🤔 html kiek matau viskas yra.

2020-08-16 10:58 UTC, wycka0214 submitted a review, later dismissed

2020-08-16 18:54 UTC, TechNaa commented
Gera praždia pusė darbo!
       Peržiūrėk savo css files: 

- Neregauoja header į ekrano pokyčius(no reponsive);
- Nerodo icon'ų;
-Taip pat link'ų spalvos.

2020-08-17 08:25 UTC, belauzas submitted a review, later dismissed

2020-08-17 08:25 UTC, belauzas commented on index.html
> +                    <div class="logo col-md-2">Laverage<span>.</span></div>
Logo reikėtų iškelti iš navigavicijos.
Pseudo struktūra:
```
header
- logo
- nav
--- a
--- a
--- a
```

2020-08-18 16:25 UTC, wycka0214 commented
.color-blue {
                color: #0474bc;
        }
 (div class="navbar logo col-md-10">
         div>  Laverage  < span class="color-blue" > .< /span> </ div)

perkelus logo klase i auksciau esantį div taskas grysta salia tekso 
ir tada span duodu klase spalvai pakeisti, bet jau man pabandzius taip padaryt - pavyko ir visa kita liko kaip buve.
![logo](https://user-images.githubusercontent.com/66961507/90539677-d09d6800-e188-11ea-8e14-9d3b938489de.png)

2020-08-18 19:43 UTC, wycka0214 requested changes
.fa klases manau isvis negalima liesti, iconu puslapyje daug ir visos igavo paddinga.
- tai savo iconoms geriau sukurk atskira (papildoma) klase  jei reikia.
- ir didesnio tarpelio tarp raketos ir buy now reiktu

![fa](https://user-images.githubusercontent.com/66961507/90558026-0f8ce700-e1a4-11ea-91ca-e1ce0944a04c.png)

2020-08-19 05:25 UTC, IngriJ commented
Still working with it :)

2020-08-19 14:57 UTC, wycka0214 submitted a review, later dismissed

2020-09-02 06:15 UTC, wycka0214 commented
Kaip reikalai su  "headeriu"? :) 
Gal ka padet?  ⏭🚀🤔😅

2020-09-04 15:43 UTC, wycka0214 approved these changes

2020-09-04 15:43 UTC, Aliux02 approved these changes

2020-09-04 15:45 UTC, devyni approved these changes

2020-09-04 15:46 UTC, merged